"""fires

Revision ID: 655cd14fbb5b
Revises: ff55457de7ee
Create Date: 2022-07-14 00:53:26.708890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655cd14fbb5b'
down_revision = 'ff55457de7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_direction_payer', table_name='direction')
    op.create_index(op.f('ix_direction_company_inn'), 'direction', ['company_inn'], unique=True)
    op.drop_constraint(None, 'direction', type_='foreignkey')
    op.create_foreign_key(None, 'direction', 'company', ['payer'], ['inn'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'direction', type_='foreignkey')
    op.create_foreign_key(None, 'direction', 'company', ['company_inn'], ['inn'])
    op.drop_index(op.f('ix_direction_company_inn'), table_name='direction')
    op.create_index('ix_direction_payer', 'direction', ['payer'], unique=False)
    # ### end Alembic commands ###
