"""payment_base

Revision ID: 65900002e107
Revises: 
Create Date: 2022-06-23 08:29:40.493289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65900002e107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_type', sa.String(length=120), nullable=True),
    sa.Column('payer_inn', sa.Integer(), nullable=True),
    sa.Column('payment_distanation', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_base_payer_inn'), 'payment_base', ['payer_inn'], unique=True)
    op.create_index(op.f('ix_payment_base_payment_date'), 'payment_base', ['payment_date'], unique=True)
    op.create_index(op.f('ix_payment_base_payment_type'), 'payment_base', ['payment_type'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_base_payment_type'), table_name='payment_base')
    op.drop_index(op.f('ix_payment_base_payment_date'), table_name='payment_base')
    op.drop_index(op.f('ix_payment_base_payer_inn'), table_name='payment_base')
    op.drop_table('payment_base')
    # ### end Alembic commands ###
