"""payment_base

Revision ID: 9c4c307223c0
Revises: 65900002e107
Create Date: 2022-06-23 08:32:53.981706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4c307223c0'
down_revision = '65900002e107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_base', sa.Column('payment_summ', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payment_base_payment_distanation'), 'payment_base', ['payment_distanation'], unique=True)
    op.create_index(op.f('ix_payment_base_payment_summ'), 'payment_base', ['payment_summ'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_base_payment_summ'), table_name='payment_base')
    op.drop_index(op.f('ix_payment_base_payment_distanation'), table_name='payment_base')
    op.drop_column('payment_base', 'payment_summ')
    # ### end Alembic commands ###
