"""'second_encounter'

Revision ID: ace2ce72c5b0
Revises: 9c4c307223c0
Create Date: 2022-06-26 23:45:31.268995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace2ce72c5b0'
down_revision = '9c4c307223c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name_payer', sa.String(length=240), nullable=True),
    sa.Column('company_name_recipient', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_base_company_name_payer'), 'company_base', ['company_name_payer'], unique=True)
    op.create_index(op.f('ix_company_base_company_name_recipient'), 'company_base', ['company_name_recipient'], unique=True)
    op.create_table('inn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payer_inn', sa.Integer(), nullable=True),
    sa.Column('recipient_inn', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inn_payer_inn'), 'inn', ['payer_inn'], unique=True)
    op.create_index(op.f('ix_inn_recipient_inn'), 'inn', ['recipient_inn'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_payment_base_payer_inn', table_name='payment_base')
    op.drop_index('ix_payment_base_payment_date', table_name='payment_base')
    op.create_index(op.f('ix_payment_base_payment_date'), 'payment_base', ['payment_date'], unique=False)
    op.drop_column('payment_base', 'payer_inn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_base', sa.Column('payer_inn', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_payment_base_payment_date'), table_name='payment_base')
    op.create_index('ix_payment_base_payment_date', 'payment_base', ['payment_date'], unique=False)
    op.create_index('ix_payment_base_payer_inn', 'payment_base', ['payer_inn'], unique=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_inn_recipient_inn'), table_name='inn')
    op.drop_index(op.f('ix_inn_payer_inn'), table_name='inn')
    op.drop_table('inn')
    op.drop_index(op.f('ix_company_base_company_name_recipient'), table_name='company_base')
    op.drop_index(op.f('ix_company_base_company_name_payer'), table_name='company_base')
    op.drop_table('company_base')
    # ### end Alembic commands ###
