"""firs data

Revision ID: b368db370d59
Revises: c93978dd3bf4
Create Date: 2022-07-06 07:54:17.777737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b368db370d59'
down_revision = 'c93978dd3bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'direction', type_='foreignkey')
    op.drop_column('direction', 'company_inn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direction', sa.Column('company_inn', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'direction', 'company', ['company_inn'], ['inn'])
    # ### end Alembic commands ###
