"""firs data

Revision ID: c93978dd3bf4
Revises: cb485101b873
Create Date: 2022-07-06 07:42:21.243172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93978dd3bf4'
down_revision = 'cb485101b873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('distanation', sa.String(length=240), nullable=True),
    sa.Column('summ', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_date'), 'payments', ['date'], unique=False)
    op.create_index(op.f('ix_payments_distanation'), 'payments', ['distanation'], unique=False)
    op.create_index(op.f('ix_payments_summ'), 'payments', ['summ'], unique=True)
    op.create_index(op.f('ix_payments_type'), 'payments', ['type'], unique=False)
    op.drop_index('ix_payment_date', table_name='payment')
    op.drop_index('ix_payment_distanation', table_name='payment')
    op.drop_index('ix_payment_summ', table_name='payment')
    op.drop_index('ix_payment_type', table_name='payment')
    op.drop_table('payment')
    op.drop_constraint(None, 'direction', type_='foreignkey')
    op.create_foreign_key(None, 'direction', 'company', ['id'], ['inn'])
    op.drop_column('direction', 'company_inn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direction', sa.Column('company_inn', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'direction', type_='foreignkey')
    op.create_foreign_key(None, 'direction', 'company', ['company_inn'], ['inn'])
    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=120), nullable=True),
    sa.Column('distanation', sa.VARCHAR(length=240), nullable=True),
    sa.Column('summ', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_type', 'payment', ['type'], unique=False)
    op.create_index('ix_payment_summ', 'payment', ['summ'], unique=False)
    op.create_index('ix_payment_distanation', 'payment', ['distanation'], unique=False)
    op.create_index('ix_payment_date', 'payment', ['date'], unique=False)
    op.drop_index(op.f('ix_payments_type'), table_name='payments')
    op.drop_index(op.f('ix_payments_summ'), table_name='payments')
    op.drop_index(op.f('ix_payments_distanation'), table_name='payments')
    op.drop_index(op.f('ix_payments_date'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
