"""relize data

Revision ID: cb485101b873
Revises: ace2ce72c5b0
Create Date: 2022-07-04 23:09:40.151769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb485101b873'
down_revision = 'ace2ce72c5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('inn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('inn')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('distanation', sa.String(length=240), nullable=True),
    sa.Column('summ', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_date'), 'payment', ['date'], unique=False)
    op.create_index(op.f('ix_payment_distanation'), 'payment', ['distanation'], unique=False)
    op.create_index(op.f('ix_payment_summ'), 'payment', ['summ'], unique=True)
    op.create_index(op.f('ix_payment_type'), 'payment', ['type'], unique=False)
    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payer', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.Integer(), nullable=True),
    sa.Column('company_inn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_inn'], ['company.inn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direction_payer'), 'direction', ['payer'], unique=True)
    op.create_index(op.f('ix_direction_recipient'), 'direction', ['recipient'], unique=True)
    op.drop_index('ix_payment_base_payment_date', table_name='payment_base')
    op.drop_index('ix_payment_base_payment_distanation', table_name='payment_base')
    op.drop_index('ix_payment_base_payment_summ', table_name='payment_base')
    op.drop_index('ix_payment_base_payment_type', table_name='payment_base')
    op.drop_table('payment_base')
    op.drop_index('ix_inn_payer_inn', table_name='inn')
    op.drop_index('ix_inn_recipient_inn', table_name='inn')
    op.drop_table('inn')
    op.drop_index('ix_company_base_company_name_payer', table_name='company_base')
    op.drop_index('ix_company_base_company_name_recipient', table_name='company_base')
    op.drop_table('company_base')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_name_payer', sa.VARCHAR(length=240), nullable=True),
    sa.Column('company_name_recipient', sa.VARCHAR(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_base_company_name_recipient', 'company_base', ['company_name_recipient'], unique=False)
    op.create_index('ix_company_base_company_name_payer', 'company_base', ['company_name_payer'], unique=False)
    op.create_table('inn',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payer_inn', sa.INTEGER(), nullable=True),
    sa.Column('recipient_inn', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inn_recipient_inn', 'inn', ['recipient_inn'], unique=False)
    op.create_index('ix_inn_payer_inn', 'inn', ['payer_inn'], unique=False)
    op.create_table('payment_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payment_date', sa.DATE(), nullable=True),
    sa.Column('payment_type', sa.VARCHAR(length=120), nullable=True),
    sa.Column('payment_distanation', sa.VARCHAR(length=240), nullable=True),
    sa.Column('payment_summ', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_base_payment_type', 'payment_base', ['payment_type'], unique=False)
    op.create_index('ix_payment_base_payment_summ', 'payment_base', ['payment_summ'], unique=False)
    op.create_index('ix_payment_base_payment_distanation', 'payment_base', ['payment_distanation'], unique=False)
    op.create_index('ix_payment_base_payment_date', 'payment_base', ['payment_date'], unique=False)
    op.drop_index(op.f('ix_direction_recipient'), table_name='direction')
    op.drop_index(op.f('ix_direction_payer'), table_name='direction')
    op.drop_table('direction')
    op.drop_index(op.f('ix_payment_type'), table_name='payment')
    op.drop_index(op.f('ix_payment_summ'), table_name='payment')
    op.drop_index(op.f('ix_payment_distanation'), table_name='payment')
    op.drop_index(op.f('ix_payment_date'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
