"""relize1

Revision ID: fed1ecc24f27
Revises: b368db370d59
Create Date: 2022-07-06 07:57:06.986549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed1ecc24f27'
down_revision = 'b368db370d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'direction', type_='foreignkey')
    op.drop_column('direction', 'company_inn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direction', sa.Column('company_inn', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'direction', 'company', ['company_inn'], ['inn'])
    # ### end Alembic commands ###
