"""'first'

Revision ID: ff55457de7ee
Revises: 
Create Date: 2022-07-12 00:37:22.228773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff55457de7ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('inn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('inn')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('distanation', sa.String(length=240), nullable=True),
    sa.Column('summ', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_date'), 'payments', ['date'], unique=False)
    op.create_index(op.f('ix_payments_distanation'), 'payments', ['distanation'], unique=False)
    op.create_index(op.f('ix_payments_summ'), 'payments', ['summ'], unique=True)
    op.create_index(op.f('ix_payments_type'), 'payments', ['type'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('direction',
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('company_inn', sa.Integer(), nullable=True),
    sa.Column('payer', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_inn'], ['company.inn'], ),
    sa.PrimaryKeyConstraint('set_number')
    )
    op.create_index(op.f('ix_direction_payer'), 'direction', ['payer'], unique=True)
    op.create_index(op.f('ix_direction_recipient'), 'direction', ['recipient'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_direction_recipient'), table_name='direction')
    op.drop_index(op.f('ix_direction_payer'), table_name='direction')
    op.drop_table('direction')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_payments_type'), table_name='payments')
    op.drop_index(op.f('ix_payments_summ'), table_name='payments')
    op.drop_index(op.f('ix_payments_distanation'), table_name='payments')
    op.drop_index(op.f('ix_payments_date'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
